version: '3.8'

services:
  app:
    image: ghcr.io/wheval/stellar_payment_api:latest
    container_name: stellar_payment_api
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      PORT: 4000
      # Add other environment variables here
    secrets:
      - db_password

secrets:
  db_password:
    file: ./secrets/db_password.txt